Add table turbot_grant and turbot_active_grants closes #12
turbot/steampipe-plugin-turbot pull request #15
Opened 2021-11-25 05:01 UTC by ParthaI

# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from turbot_active_grant
+-----------------+--------+-----------------------+-----------------------+-------------+----------------+----------------------+-----------------------+------------------------------------------------------+------------------------+------------------------------------
| id              | status | display_name          | email                 | family_name | given_name     | last_login_timestamp | profile_id            | grant_identity_trunk_title                           | grant_type_trunk_title | resource_trunk_title               
+-----------------+--------+-----------------------+-----------------------+-------------+----------------+----------------------+-----------------------+------------------------------------------------------+------------------------+------------------------------------
| 187955963950910 | Active | Rajesh Mohanty        | raj@turbot.com        | Mohanty     | Rajesh         | 2021-11-12T12:55:01Z | raj@turbot.com        | Turbot > Google @ turbot.com > Rajesh Mohanty        | AWS                    | Turbot                             
| 228825783324327 | Active | Sourav Chakraborty    | sourav@turbot.com     | Chakraborty | Sourav         | 2021-11-16T09:47:31Z | sourav@turbot.com     | Turbot > Google @ turbot.com > Sourav Chakraborty    | Turbot                 | Turbot                             
| 162654220537467 | Active | Cody Bruno            | cody@turbot.com       | Bruno       | Cody           | 2021-10-12T15:11:28Z | cody@turbot.com       | Turbot > Google @ turbot.com > Cody Bruno            | Turbot                 | Turbot                             
| 228825783263908 | Active | Sourav Chakraborty    | sourav@turbot.com     | Chakraborty | Sourav         | 2021-11-16T09:47:31Z | sourav@turbot.com     | Turbot > Google @ turbot.com > Sourav Chakraborty    | AWS                    | Turbot                             
| 162687943115559 | Active | Victor Hadianto       | victor@turbot.com     | Hadianto    | Victor         | 2020-12-08T04:15:27Z | victor@turbot.com     | Turbot > Google @ turbot.com > Victor Hadianto       | Turbot                 | Turbot                             
| 162199372745414 | Active | Mike Burgess          | mike@turbot.com       | Burgess     |                | 2019-06-14T09:24:33Z | mike@turbot.com       | Turbot > Turbot Local > Mike Burgess                 | Turbot                 | Turbot                             
| 165127151384153 | Active | Venugopal Rao Kumbha  | venu@turbot.com       | Kumbha      | Venugopal Rao  | 2021-05-03T09:18:35Z | venu@turbot.com       | Turbot > Google @ turbot.com > Venugopal Rao Kumbha  | Turbot                 | Turbot                             
| 187951537041105 | Active | Rajesh Mohanty        | raj@turbot.com        | Mohanty     | Rajesh         | 2021-11-12T12:55:01Z | raj@turbot.com        | Turbot > Google @ turbot.com > Rajesh Mohanty        | Turbot                 | Turbot                             
| 165127151384155 | Active | Puskar Basu           | puskar@turbot.com     | Basu        | Puskar         | 2019-07-22T07:03:13Z | puskar@turbot.com     | Turbot > Google @ turbot.com > Puskar Basu           | Turbot                 | Turbot                             
| 186382714186737 | Active | Cody Bruno            | cody@turbot.com       | Bruno       | Cody           | 2021-10-12T15:11:28Z | cody@turbot.com       | Turbot > Google @ turbot.com > Cody Bruno            | Turbot                 | Turbot                             
| 161241086058469 | Active | Turbot Admin          | admin@turbot.io       | Admin       | Turbot         | 2020-03-12T20:32:42Z | admin@turbot.io       | Turbot > Turbot Local > Turbot Admin                 | Turbot                 | Turbot                             
| 188609043733045 | Active | Mike Burgess          | mike@turbot.com       | Burgess     | Mike           | 2020-12-17T12:40:08Z | mike@turbot.com       | Turbot > Google @ turbot.com > Mike Burgess          | Turbot                 | Turbot                             
| 232513631798826 | Active | Partha Sarathi Behera | partha@turbot.com     | Behera      | Partha Sarathi | 2021-11-24T04:48:44Z | partha@turbot.com     | Turbot > Google @ turbot.com > Partha Sarathi Behera | Turbot                 | Turbot > AWS Accounts > 82868500162
| 188609043827255 | Active | Nathan Wallace        | nathan@turbot.com     | Wallace     | Nathan         | 2020-12-08T02:30:26Z | nathan@turbot.com     | Turbot > Google @ turbot.com > Nathan Wallace        | Turbot                 | Turbot                             
| 161525342506570 | Active | John Smyth            | john@turbot.com       | Smyth       |                | 2019-07-24T22:48:27Z | john@turbot.com       | Turbot > Turbot Local > John Smyth                   | Turbot                 | Turbot                             
| 232514599378941 | Active | Lalit Bhardwaj        | lalit@turbot.com      | Bhardwaj    | Lalit          | 2021-10-22T07:32:00Z | lalit@turbot.com      | Turbot > Google @ turbot.com > Lalit Bhardwaj        | AWS                    | Turbot > AWS Accounts > 82868500162
| 232513632812589 | Active | Partha Sarathi Behera | partha@turbot.com     | Behera      | Partha Sarathi | 2021-11-24T04:48:44Z | partha@turbot.com     | Turbot > Google @ turbot.com > Partha Sarathi Behera | AWS                    | Turbot > AWS Accounts > 82868500162
| 229155810665565 | Active | Partha Sarathi Behera | partha@turbot.com     | Behera      | Partha Sarathi | 2021-11-24T04:48:44Z | partha@turbot.com     | Turbot > Google @ turbot.com > Partha Sarathi Behera | AWS                    | Turbot                             
| 240323832925644 | Active | Ved Misra             | ved@turbot.com        | Misra       | Ved            | 2021-11-15T14:16:59Z | ved@turbot.com        | Turbot > Google @ turbot.com > Ved Misra             | Turbot                 | Turbot > AWS Accounts              
| 240323894688215 | Active | Ved Misra             | ved@turbot.com        | Misra       | Ved            | 2021-11-15T14:16:59Z | ved@turbot.com        | Turbot > Google @ turbot.com > Ved Misra             | AWS                    | Turbot > AWS Accounts              
| 189793356659129 | Active | Lalit Bhardwaj        | lalit@turbot.com      | Bhardwaj    | Lalit          | 2021-10-22T07:32:00Z | lalit@turbot.com      | Turbot > Google @ turbot.com > Lalit Bhardwaj        | Turbot                 | Turbot                             
| 216704470461792 | Active | Siddhartha Das        | siddhartha@turbot.com | Das         | Siddhartha     | 2021-05-17T08:18:20Z | siddhartha@turbot.com | Turbot > Google @ turbot.com > Siddhartha Das        | Turbot                 | Turbot                             
| 189875992293779 | Active | Lalit Bhardwaj        | lalit@turbot.com      | Bhardwaj    | Lalit          | 2021-10-22T07:32:00Z | lalit@turbot.com      | Turbot > Google @ turbot.com > Lalit Bhardwaj        | AWS                    | Turbot > AWS Accounts > 82868500162
| 212996033941661 | Active | Abhinash Khuntia      | abhinash@turbot.com   | Khuntia     | Abhinash       | 2021-05-17T08:18:19Z | abhinash@turbot.com   | Turbot > Google @ turbot.com > Abhinash Khuntia      | Turbot                 | Turbot                             
+-----------------+--------+-----------------------+-----------------------+-------------+----------------+----------------------+-----------------------+------------------------------------------------------+------------------------+------------------------------------
```
</details>

2021-11-25 07:18 UTC, rajlearner17 commented on turbot/turbot_active_grant.go
> +			{Name: "id", Type: proto.ColumnType_INT, Transform: transform.FromField("Turbot.ID"), Description: "Unique identifier of the grant."},
```suggestion
			{Name: "id", Type: proto.ColumnType_INT, Transform: transform.FromField("Turbot.ID"), Description: "Unique identifier of the grant."},
```
grant > grantee

2021-11-25 07:33 UTC, rajlearner17 commented
@ParthaI I would suggest having a `turbot_grant` table to capture grantee with status (Active/Inactive) and associated grants (Permissions)

2021-12-07 16:31 UTC, cbruno10 requested changes
Please see suggestions

General guidelines:
- Convert the field name into snake case
- Omit the word `turbot` in the column name
- Sometimes add the word `grant` or `active_grant` if there's ambiguity with another column name that's very close, e.g., `identity_status` vs. `grant_status`

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "grantee_status", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.Status"), Description: "Status of the grantee."},
```suggestion
			{Name: "identity_status", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.Status"), Description: "Status of the grantee."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "display_name", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.DisplayName"), Description: "Display name of the grantee."},
```suggestion
			{Name: "identity_display_name", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.DisplayName"), Description: "Display name of the grantee."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "grant_identity_trunk_title", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.Trunk.Title"), Description: "Full title (including ancestor trunk) of the grant identit
```suggestion
			{Name: "identity_trunk_title", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.Trunk.Title"), Description: "Full title (including ancestor trunk) of the grant identity."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "last_login_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Identity.LastLoginTimestamp"), Description: "Last login timestamp for the login."},
```suggestion
			{Name: "identity_last_login_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Identity.LastLoginTimestamp"), Description: "Last login timestamp for the login."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "grant_type_trunk_title", Type: proto.ColumnType_STRING, Transform: transform.FromField("Type.Trunk.Title"), Description: "Full title (including ancestor trunk) of the grant type."},
```suggestion
			{Name: "type_trunk_title", Type: proto.ColumnType_STRING, Transform: transform.FromField("Type.Trunk.Title"), Description: "Full title (including ancestor trunk) of the grant type."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "grant_type_uri", Type: proto.ColumnType_STRING, Transform: transform.FromField("Type.URI"), Description: "URI of the grant type."},
```suggestion
			{Name: "type_uri", Type: proto.ColumnType_STRING, Transform: transform.FromField("Type.URI"), Description: "URI of the grant type."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "profile_id", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.ProfileID"), Description: "Profile id of the grantee."},
```suggestion
			{Name: "identity_profile_id", Type: proto.ColumnType_STRING, Transform: transform.FromField("Identity.ProfileID"), Description: "Profile id of the grantee."},
```

2021-12-07 16:31 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "akas", Type: proto.ColumnType_JSON, Transform: transform.FromField("Identity.Akas"), Description: "AKA (also known as) identifiers for the grantee"},
```suggestion
			{Name: "identity_akas", Type: proto.ColumnType_JSON, Transform: transform.FromField("Identity.Akas"), Description: "AKA (also known as) identifiers for the grantee"},
```

2021-12-08 13:15 UTC, rajlearner17 commented on turbot/table_turbot_grant.go
> +		{Name: "id", Type: proto.ColumnType_INT, Transform: transform.FromField("Turbot.ID"), Description: "Unique identifier of the grantee."},
```suggestion
		{Name: "id", Type: proto.ColumnType_INT, Transform: transform.FromField("Turbot.ID"), Description: "Unique identifier of the identity."},
```

2021-12-08 13:16 UTC, rajlearner17 commented on turbot/table_turbot_grant.go
> +		{Name: "id", Type: proto.ColumnType_INT, Transform: transform.FromField("Turbot.ID"), Description: "Unique identifier of the grantee."},
change grantee > identity

2021-12-08 13:20 UTC, rajlearner17 commented on turbot/table_turbot_grant.go
> +		{Name: "identity_last_login_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Identity.LastLoginTimestamp"), Description: "Last login timestamp for the login."},
```suggestion
		{Name: "identity_last_login_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Identity.LastLoginTimestamp"), Description: "Last login timestamp."},
```

2021-12-08 13:23 UTC, rajlearner17 commented on turbot/table_turbot_grant.go
> +		{Name: "update_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Turbot.UpdateTimestamp"), Description: "When the tag grant last updated in Turbot."},
```suggestion
		{Name: "update_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Turbot.UpdateTimestamp"), Description: "When the grant was last updated in Turbot"},
```

2021-12-08 13:25 UTC, rajlearner17 commented on turbot/table_turbot_grant.go
> +		{Name: "create_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Turbot.CreateTimestamp").NullIfEqual(""), Description: "The create time of grant."},
```suggestion
		{Name: "create_timestamp", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromField("Turbot.CreateTimestamp").NullIfEqual(""), Description: "The create time of the grant."},
```

2022-01-11 15:36 UTC, cbruno10 requested changes
@ParthaI Please see comments, thanks!

A lot of comments are around field naming, we had established some guidelines in https://github.com/turbot/steampipe-plugin-turbot/pull/15#pullrequestreview-825513447, was there a reason you deviated from these here?

Also, I think there's a similar column naming issue I didn't include in this review, but did for active_grant here https://github.com/turbot/steampipe-plugin-turbot/pull/24#discussion_r782269061.

2022-01-11 15:36 UTC, cbruno10 commented on docs/tables/turbot_grant.md
> +## Examples
We should include 3-4 more useful examples

2022-01-11 15:36 UTC, cbruno10 commented on turbot/table_turbot_grant.go
> +			{Name: "type_trunk_title", Type: proto.ColumnType_STRING, Transform: transform.FromField("Resource.Type.Trunk.Title"), Description: "Full title (including ancestor trunk) of the grant type."},
Why does this column and the one below not include the word `resource`, but the others below it do with similar property paths?

2022-01-24 14:03 UTC, cbruno10 approved these changes

2022-01-24 14:04 UTC, merged